services:
  kms:
    network_mode: host
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - BASE_CCF_IMAGE=${CCF_VERSION:-5.0.0-rc0}
        - CCF_PLATFORM=${CCF_PLATFORM:-virtual}