name: "KMS CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  kms:
    name: kms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build DevContainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          configFile: .devcontainer/devcontainer.json
          runCmd: |
            make demo && npm run test
        env:
          KMS_WORKSPACE: ./workspace

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: KMS Lint
        run: make lint
